"use client";

export default function Expenses() {
  return <h1>Expenses</h1>;
  //     bossing eto yung supabase table ng Expenses

  //     create table public.expenses (
  //   id bigint generated by default as identity not null,
  //   created_at timestamp with time zone not null default now(),
  //   description text null,
  //   amount double precision null,
  //   constraint expenses_pkey primary key (id)
  // ) TABLESPACE pg_default;
}
