"use client";

import AddButton from "../../components/AddButton";
import { useState, useEffect } from "react";

export default function Expenses() {
  const fetchExpenses = () => {
    console.log("Fetching updated expenses...");
  };

  return (
    <div className="container p-6">
      {/* Page Title */}
      <h2 className="text-white text-xl font-semibold mb-4">
        Expenses Management
      </h2>

      {/* Buttons Row */}
      <div className="flex flex-wrap gap-2 mb-4">
        <AddButton
          table="expenses"
          fields={[
            { key: "description", label: "Description", type: "text" },
            { key: "amount", label: "Amount", type: "number" },
          ]}
          onSuccess={fetchExpenses}
        />
      </div>

      {/* Table Container */}
      <div className="bg-white rounded-md shadow overflow-hidden text-black">
        {/* Table Header (placeholder like Categories page) */}
        <div className="border-b px-4 py-3 font-semibold">
          Expenses List
        </div>

        {/* Table Body Placeholder */}
        <div className="p-4 text-sm text-gray-500">
          {/* Dito papasok ang DataTable mo */}
          No data available.
        </div>
      </div>
    </div>
  );
}

//     bossing eto yung supabase table ng Expenses

//   create table public.expenses (
//   id bigint generated by default as identity not null,
//   created_at timestamp with time zone not null default now(),
//   description text null,
//   amount double precision null,
//   constraint expenses_pkey primary key (id)
// ) TABLESPACE pg_default;
